export const HEADLINES_REQUEST = "HEADLINES_REQUEST";
export const HEADLINES_FAILURE = "HEADLINES_FAILURE";
export const HEADLINES_SUCCESS = "HEADLINES_SUCCESS";
export const HEADLINES_INCREASE_PAGE = "HEADLINES_INCREASE_PAGE";
export const HEADLINES_KEYWORD = "HEADLINES_KEYWORD";
